"""Deterministic-only constants for Evidence v4 e2e pytest suite.

Only values written into seed-demo.ts as STRING LITERALS live here. Anything
generated by `uuid()` at seed-time (repo_id / scan_id / finding_id) MUST be
discovered at runtime via the `discovered` fixture in conftest.py — see the
2026-04-21 parallel-session sync note that hardcoded UUIDs go stale every
re-seed and surface as 404 (not skip).

REPO_NAME stays a constant because seed-demo writes it as a literal string.
"""
PROJECT = "c:/tmp/cl-sub3b-e2e"
DB_PATH = "c:/AI/ComplianceLint/private/dashboard/data/compliancelint.db"
SAAS = "http://localhost:3000"
API_KEY = "cl_test_pro_key_for_development"
REPO_NAME = "test-pro/demo-highrisk-provider"
